x-app-php-attributes: &app-php-attributes
  image: ${IMAGES_PREFIX:-}app-php
  restart: unless-stopped
  healthcheck:
    test: [ "CMD", "healthcheck" ]
    interval: 10s
    timeout: 3s
    retries: 10
    start_period: 60s
  depends_on:
    app-database:
      condition: service_healthy
  command: ["php-fpm", "-F"]

x-app-database-attributes: &app-database-attributes
  image: postgres:${POSTGRES_VERSION:-18}-alpine
  restart: unless-stopped
  healthcheck:
    test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-dbname}", "-U", "${POSTGRES_USER:-user}" ]
    timeout: 5s
    retries: 5
    start_period: 60s

x-app-nginx-attributes: &app-nginx-attributes
  image: ${IMAGES_PREFIX:-}app-nginx
  build:
    context: .
    target: nginx_dev
  restart: unless-stopped
  depends_on:
    app-php:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "nc -vz -w1 $(hostname) 80"]
    interval: 10s
    timeout: 5s
    retries: 5

x-app-mailer-attributes: &app-mailer-attributes
  image: axllent/mailpit

services:
  app-php: *app-php-attributes
  app-database: *app-database-attributes
  app-nginx: *app-nginx-attributes
  app-mailer: *app-mailer-attributes
