name: Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  tests:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: dbname
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo, pdo_pgsql, mbstring, xml, ctype, iconv
          coverage: pcov
          tools: phpunit

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache vendor directory
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-vendor-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Set up database
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:schema:create --env=test
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/dbname?serverVersion=15&charset=utf8

      - name: Generate JWT keys and a test token
        run: |
          php bin/console lexik:jwt:generate-keypair --overwrite -n
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/dbname?serverVersion=15&charset=utf8

      - name: Run tests
        run: composer run tests
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/dbname?serverVersion=15&charset=utf8
